# Generated by Django 5.0.2 on 2024-02-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsapp', '0003_vehicle_vehicle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitycheck',
            name='pass_fail',
        ),
        migrations.RemoveField(
            model_name='qualitycheck',
            name='security_department',
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Pass', 'Pass'), ('Fail', 'Fail')], default='Processing', max_length=20),
        ),
    ]
