# Generated by Django 5.0.2 on 2024-02-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsapp', '0004_remove_qualitycheck_pass_fail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycheck',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_check', to='vmsapp.vehicle'),
        ),
    ]
