# Generated by Django 5.0.2 on 2024-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsapp', '0005_alter_qualitycheck_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
